# Generated by Django 4.0.2 on 2022-02-07 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='walletaccount',
            name='account_ptr',
        ),
        migrations.RemoveField(
            model_name='walletaccount',
            name='wallet',
        ),
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.DeleteModel(
            name='Wallet',
        ),
        migrations.DeleteModel(
            name='WalletAccount',
        ),
    ]
